import type { Client, DailyLog } from "./types";

export const clients: Client[] = [
  {
    id: "c1",
    name: "Kyle Ferguson",
    company: "Ferguson Enterprises",
    industry: "Home Services",
    status: "Active",
    engagement: "Full-time",
    schedule: "M-F (8AM-5PM)",
    rate: 2500,
    rateLabel: "$2,500/mo",
    joinedDate: "2026-01-15",
    avatar: "KF",
  },
  {
    id: "c2",
    name: "Sarah Chen",
    company: "Smile Dental Co",
    industry: "Dental",
    status: "Active",
    engagement: "Part-time",
    schedule: "M-W-F (9AM-1PM)",
    rate: 1800,
    rateLabel: "$1,800/mo",
    joinedDate: "2026-02-10",
    avatar: "SC",
  },
  {
    id: "c3",
    name: "Marcus Johnson",
    company: "FitLife Gym",
    industry: "Fitness",
    status: "Onboarding",
    engagement: "Project-based",
    schedule: "Flexible",
    rate: 4500,
    rateLabel: "$4,500 (project)",
    joinedDate: "2026-04-01",
    avatar: "MJ",
  },
  {
    id: "c4",
    name: "Emily Park",
    company: "Realty Plus",
    industry: "Real Estate",
    status: "Active",
    engagement: "Full-time",
    schedule: "M-F (8AM-5PM)",
    rate: 3000,
    rateLabel: "$3,000/mo",
    joinedDate: "2025-11-20",
    avatar: "EP",
  },
  {
    id: "c5",
    name: "Tom Rivera",
    company: "Peak Coaching",
    industry: "Coaching",
    status: "Paused",
    engagement: "Part-time",
    schedule: "T-Th (10AM-3PM)",
    rate: 1200,
    rateLabel: "$1,200/mo",
    joinedDate: "2025-09-05",
    avatar: "TR",
  },
];

export const dailyLog: DailyLog = {
  id: "d1",
  date: "2026-04-16",
  timeIn: "08:30 AM",
  timeOut: "",
  tasksCompleted: [
    "Client onboarding call",
    "Updated CRM pipeline stages",
  ],
  pendingTasks: [
    "Build landing page v2",
    "Fix broken webhook",
  ],
  priorities: [
    "Fix webhook (blocking lead flow)",
    "Landing page - client expecting preview tomorrow",
  ],
  blockers: [
    "Waiting on brand assets from client",
  ],
  nextDayPlan: [
    "Finish landing page",
    "Start Facebook ad creatives",
    "Review funnel A/B results",
  ],
};
